In [1]:
from pprint import pprint

### Q2)

Write Python code to multiply the above two matrices. Solve using list of lists and then use numpy. Compare the timing of both solutions. Which one is faster? Why?

### Answer)

In [2]:
# Define the matrices of n = 5, k = 10, m = 6
from random import randint

A = [[randint(1000, 2000) for _ in range(10)] for _ in range(5)]
B = [[randint(1000, 2000) for _ in range(6)] for _ in range(10)]

In [3]:
def matrix_multiplication(A, B):
    n = len(A)
    k = len(B)
    m = len(B[0])

    C = [[0 for _ in range(m)] for _ in range(n)]

    # row of A
    for r in range(n):
        # column of B
        for c in range(m):
            for i in range(k):
                C[r][c] += (A[r][i] * B[i][c])

    return C


def matrix_multiplication_numpy(A, B):
    import numpy as np

    return np.matmul(A, B)

pprint(matrix_multiplication(A, B))
pprint(list(matrix_multiplication_numpy(A, B)))

[[22391732, 21971908, 21512835, 21513264, 22808529, 22212048],
 [24125480, 23241538, 23313032, 23451906, 24427646, 24065514],
 [23495361, 22606788, 22523128, 21846148, 22922905, 23276011],
 [25198259, 24109855, 24005631, 23931232, 25129453, 24510346],
 [24622096, 23476562, 23493167, 23401071, 24266989, 24224933]]
[array([22391732, 21971908, 21512835, 21513264, 22808529, 22212048]),
 array([24125480, 23241538, 23313032, 23451906, 24427646, 24065514]),
 array([23495361, 22606788, 22523128, 21846148, 22922905, 23276011]),
 array([25198259, 24109855, 24005631, 23931232, 25129453, 24510346]),
 array([24622096, 23476562, 23493167, 23401071, 24266989, 24224933])]


In [4]:
%timeit matrix_multiplication(A, B)

48.3 µs ± 1.07 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [5]:
%timeit matrix_multiplication_numpy(A, B)

9.81 µs ± 34.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


Comparing the timing of both solutions, the numpy solution is faster. This is because numpy is implemented in C, which is faster than Python.