### Q1)

How many multiplications and additions do you need to perform a matrix multiplication between a (n, k) and (k, m) matrix? Explain.

### Answer)

#### Multiplications
- Given A (n, k) and B (k, m) matrices.
- Row of A & Column of B has k multiplication.
- The row is multiplied by all the `m columns` of B, so `k * m` multiplications for a row.
- All the `n rows of A` are subjected to the above operation, so `n * k * m` multiplications.


#### Additions
- Given A (n, k) and B (k, m) matrices.
- Row of A & Column of B has k - 1 additions.
- The row is multiplied by all the `m columns` of B, so `m * (k - 1)` additions for a row.
- All the `n rows of A` are subjected to the above operation, so `n * m * (k - 1)` additions.


### Q2)

Write Python code to multiply the above two matrices. Solve using list of lists and then use numpy. Compare the timing of both solutions. Which one is faster? Why?

### Answer)

In [17]:
# Define the matrices of n = 5, k = 10, m = 6
from random import randint

A = [[randint(1000, 2000) for _ in range(10)] for _ in range(5)]
B = [[randint(1000, 2000) for _ in range(6)] for _ in range(10)]

In [18]:
from pprint import pprint

def matrix_multiplication(A, B):
    n = len(A)
    k = len(B)
    m = len(B[0])

    C = [[0 for _ in range(m)] for _ in range(n)]

    # row of A
    for r in range(n):
        # column of B
        for c in range(m):
            for i in range(k):
                C[r][c] += (A[r][i] * B[i][c])

    return C


def matrix_multiplication_numpy(A, B):
    import numpy as np

    return np.matmul(A, B)

pprint(matrix_multiplication(A, B))
pprint(list(matrix_multiplication_numpy(A, B)))

[[22575890, 22800707, 23984723, 23744898, 22688090, 19904627],
 [21936713, 21959146, 23264714, 23062893, 21605418, 19063967],
 [22710404, 22992604, 23886690, 23793250, 22738238, 19313036],
 [19801988, 20222719, 21113283, 21226116, 20149875, 16990289],
 [19439942, 20284745, 20981956, 21474734, 19362069, 17123405]]
[array([22575890, 22800707, 23984723, 23744898, 22688090, 19904627]),
 array([21936713, 21959146, 23264714, 23062893, 21605418, 19063967]),
 array([22710404, 22992604, 23886690, 23793250, 22738238, 19313036]),
 array([19801988, 20222719, 21113283, 21226116, 20149875, 16990289]),
 array([19439942, 20284745, 20981956, 21474734, 19362069, 17123405])]


In [19]:
%timeit matrix_multiplication(A, B)

51 µs ± 1.15 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [20]:
%timeit matrix_multiplication_numpy(A, B)

9.84 µs ± 98 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


Comparing the timing of both solutions, the numpy solution is faster. This is because numpy is implemented in C, which is faster than Python.